services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - RUNTIPI_HOST=${RUNTIPI_HOST}
      - RUNTIPI_USERNAME=${RUNTIPI_USERNAME}
      - RUNTIPI_PASSWORD=${RUNTIPI_PASSWORD}
    volumes:
      - "${SCRIPTS_PATH}:/scripts:ro"  # Read-only para segurança
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Docker socket (read-only)
    networks:
      - runtipi_tipi_main_network
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=telegram-bot"
networks:
  runtipi_tipi_main_network:
    external: true