services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - RUNTIPI_HOST=${RUNTIPI_HOST}
      - RUNTIPI_USERNAME=${RUNTIPI_USERNAME}
      - RUNTIPI_PASSWORD=${RUNTIPI_PASSWORD}
    volumes:
      - "${SCRIPTS_PATH}:/scripts"
    networks:
      - runtipi_tipi_main_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=telegram-bot"
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:7777/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
networks:
  runtipi_tipi_main_network:
    external: true