name: Build and Push Docker Image

# Executa este workflow sempre que houver um push na branch 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Clona o repositório para o ambiente de execução
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Faz login no Docker Hub usando os secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Constrói a imagem e envia para o Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: seu-usuario/nome-da-sua-imagem:latest # <-- Altere aqui!